import logging
import os
import time
import importlib
import threading
import uuid
from contextlib import nullcontext

from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

import boto3
from bedrock_agentcore.runtime import BedrockAgentCoreApp


def _env_flag(name: str, default: str = "0") -> bool:
    value = (os.getenv(name, default) or "").strip().lower()
    return value in {"1", "true", "yes", "y", "on"}


LANGFUSE_ENABLED = _env_flag("LANGFUSE_ENABLED", "0")

langfuse = None
if LANGFUSE_ENABLED:
    try:
        from langfuse import get_client

        langfuse = get_client()

        CrewAIInstrumentor = importlib.import_module(
            "openinference.instrumentation.crewai"
        ).CrewAIInstrumentor
        CrewAIInstrumentor().instrument(skip_dep_check=True)

        try:
            BedrockInstrumentor = importlib.import_module(
                "openinference.instrumentation.bedrock"
            ).BedrockInstrumentor
            BedrockInstrumentor().instrument()
            logger.info(
                "OpenInference Bedrock instrumentation enabled (LLM/Converse spans for Langfuse)"
            )
        except ImportError:
            logger.warning(
                "openinference-instrumentation-bedrock not installed; Bedrock LLM calls may be missing "
                "from Langfuse. Install with: pip install openinference-instrumentation-bedrock"
            )

        # Suppress low-level HTTP spans (GET/PUT/etc.) generated by boto3's underlying
        # HTTP calls — these clutter the Langfuse graph without adding useful information
        # since BedrockInstrumentor already captures the higher-level Converse API spans.
        for module_path, cls_name in [
            ("opentelemetry.instrumentation.requests", "RequestsInstrumentor"),
            ("opentelemetry.instrumentation.urllib3", "URLLib3Instrumentor"),
            ("opentelemetry.instrumentation.httpx", "HTTPXClientInstrumentor"),
        ]:
            try:
                instrumentor_cls = importlib.import_module(module_path)
                getattr(instrumentor_cls, cls_name)().uninstrument()
                logger.info("Suppressed HTTP spans from %s", cls_name)
            except (ImportError, AttributeError):
                pass

        # Re-add Textract at the botocore level so calls appear as named spans
        # (e.g. "textract.start_document_text_detection") instead of raw GET/PUT.
        try:
            BotocoreInstrumentor = importlib.import_module(
                "opentelemetry.instrumentation.botocore"
            ).BotocoreInstrumentor
            BotocoreInstrumentor().instrument(service_whitelist=["textract"])
            logger.info("Botocore Textract instrumentation enabled")
        except (ImportError, AttributeError):
            logger.warning(
                "opentelemetry-instrumentation-botocore not installed; Textract spans will be missing. "
                "Install with: pip install opentelemetry-instrumentation-botocore"
            )

        from crew.langfuse_crewai_patches import patch_crewai_structured_tool_for_langfuse

        patch_crewai_structured_tool_for_langfuse()
        logger.info("Langfuse enabled (LANGFUSE_ENABLED=1)")
    except Exception:
        logger.exception("Langfuse init failed; continuing without Langfuse")
        langfuse = None
else:
    logger.info("Langfuse disabled (set LANGFUSE_ENABLED=1 to enable)")

from crew.crew import KYCCrew, OverrideValidationCrew


app = BedrockAgentCoreApp()

# if langfuse.auth_check():
#     logger.info("✅ Langfuse authentication successful")
# else:
#     logger.error("❌ Langfuse authentication failed")

def get_ssm_parameter(name: str, with_decryption: bool = True, *, ssm_client=None) -> str:
    """Get a parameter value from AWS Systems Manager Parameter Store."""
    ssm = ssm_client or boto3.client("ssm")
    response = ssm.get_parameter(Name=name, WithDecryption=with_decryption)

    value = response["Parameter"]["Value"]
    logger.info(
        "Fetched SSM parameter: %s with_decryption=%s value=%s",
        name,
        with_decryption,
        value,
    )
    return value


_MODEL_SSM_PARAM_NAME = "/kyc-agent/model-id"
_MODEL_LAST_REFRESH_EPOCH = 0.0


def ensure_model_env_from_ssm(*, max_age_seconds: int = 300, force: bool = False) -> None:
    """Ensure os.environ['MODEL'] is populated from SSM.

    AgentCore runtimes are long-lived; if you change the SSM parameter, the process
    won't pick it up unless we refresh. This helper refreshes with a TTL to avoid
    calling SSM on every request.
    """
    global _MODEL_LAST_REFRESH_EPOCH

    now = time.time()
    if not force and (now - _MODEL_LAST_REFRESH_EPOCH) < max_age_seconds and os.environ.get("MODEL"):
        return

    logger.info("Refreshing MODEL from SSM Parameter Store (param=%s)...", _MODEL_SSM_PARAM_NAME)
    try:
        os.environ["MODEL"] = get_ssm_parameter(_MODEL_SSM_PARAM_NAME)
        _MODEL_LAST_REFRESH_EPOCH = now
        logger.info("✅ MODEL environment variable set to: %s", os.environ.get("MODEL"))
    except Exception as e:
        logger.error("❌ Failed to set MODEL Id from SSM: %s", e)


# Initial best-effort set at startup (cold start)
ensure_model_env_from_ssm(max_age_seconds=0, force=True)


def _langfuse_span(name: str):
    if not langfuse:
        return nullcontext()
    try:
        return langfuse.start_as_current_observation(as_type="span", name=name)
    except Exception:
        logger.exception("Failed to start Langfuse span; continuing")
        return nullcontext()


def _run_kyc_crew_background(*, case_id: str, job_id: str) -> None:
    try:
        logger.info("[job=%s] Background KYC kickoff starting (caseId=%s)", job_id, case_id)
        ensure_model_env_from_ssm(max_age_seconds=int(os.getenv("MODEL_SSM_REFRESH_SECONDS", "300")))
        with _langfuse_span("crewai-index-trace"):
            result = KYCCrew().crew().kickoff(inputs={"caseId": case_id})
            logger.info("[job=%s] Background KYC kickoff finished (caseId=%s)", job_id, case_id)
            try:
                logger.info("[job=%s] Result: %s", job_id, result.raw)
            except Exception:
                logger.info("[job=%s] Result produced (raw unavailable)", job_id)

        if langfuse:
            try:
                langfuse.flush()
            except Exception:
                logger.exception("[job=%s] Langfuse flush failed; continuing", job_id)
    except Exception:
        logger.exception("[job=%s] Background kickoff failed (caseId=%s)", job_id, case_id)


def _run_override_validation_background(*, case_id: str, analyst_comments: str, job_id: str) -> None:
    try:
        logger.info("[job=%s] Override validation starting (caseId=%s)", job_id, case_id)
        ensure_model_env_from_ssm(max_age_seconds=int(os.getenv("MODEL_SSM_REFRESH_SECONDS", "300")))
        with _langfuse_span("override-validation-trace"):
            result = OverrideValidationCrew().crew().kickoff(inputs={
                "caseId": case_id,
                "analystComments": analyst_comments,
            })
            logger.info("[job=%s] Override validation finished (caseId=%s)", job_id, case_id)
            try:
                logger.info("[job=%s] Result: %s", job_id, result.raw)
            except Exception:
                logger.info("[job=%s] Result produced (raw unavailable)", job_id)

        if langfuse:
            try:
                langfuse.flush()
            except Exception:
                logger.exception("[job=%s] Langfuse flush failed; continuing", job_id)
    except Exception:
        logger.exception("[job=%s] Override validation failed (caseId=%s)", job_id, case_id)




@app.entrypoint
def agent_invocation(payload, context):
    """
    Handler for KYC screening.
    Payload must include caseId. Optionally KYC_CASES_TABLE env var for DynamoDB table name.
    Returns JSON with name, analysis_result, analysis_summary.
    """
    try:
        # Refresh MODEL periodically so SSM changes take effect without a restart
        ensure_model_env_from_ssm(max_age_seconds=int(os.getenv("MODEL_SSM_REFRESH_SECONDS", "300")))

        case_id = payload.get("caseId", "").strip()
        if not case_id:
            logger.warning("No caseId provided in payload")
            return {"error": "Missing 'caseId' in payload"}

        analyst_comments = payload.get("analystComments", "").strip()

        job_id = str(uuid.uuid4())

        if analyst_comments:
            logger.info("Override validation request for caseId: %s", case_id)
            thread = threading.Thread(
                target=_run_override_validation_background,
                kwargs={"case_id": case_id, "analyst_comments": analyst_comments, "job_id": job_id},
                name=f"kyc-override-{job_id}",
                daemon=True,
            )
            thread.start()
            return {"status": "override_review_started", "caseId": case_id, "jobId": job_id}

        logger.info("KYC screening for caseId: %s", case_id)
        thread = threading.Thread(
            target=_run_kyc_crew_background,
            kwargs={"case_id": case_id, "job_id": job_id},
            name=f"kyc-kickoff-{job_id}",
            daemon=True,
        )
        thread.start()
        return {"status": "started", "caseId": case_id, "jobId": job_id}

    except Exception as e:
        logger.exception("Agent invocation failed")
        return {"error": str(e)}


def test_kyc_flow(case_id: str) -> None:
    """Run KYC crew synchronously — for local testing only."""
    logger.info("test_kyc_flow: caseId=%s", case_id)
    ensure_model_env_from_ssm(max_age_seconds=0, force=True)
    with _langfuse_span("crewai-index-trace"):
        result = KYCCrew().crew().kickoff(inputs={"caseId": case_id})
    logger.info("test_kyc_flow result: %s", result.raw)


def test_override_flow(case_id: str, analyst_comments: str) -> None:
    """Run override validation crew synchronously — for local testing only."""
    logger.info("test_override_flow: caseId=%s comments=%r", case_id, analyst_comments)
    ensure_model_env_from_ssm(max_age_seconds=0, force=True)
    with _langfuse_span("override-validation-trace"):
        result = OverrideValidationCrew().crew().kickoff(inputs={
            "caseId": case_id,
            "analystComments": analyst_comments,
        })
    logger.info("test_override_flow result: %s", result.raw)


if __name__ == "__main__":
    import sys

    # Usage:
    #   python -m crew.kyc_app kyc <caseId>
    #   python -m crew.kyc_app override <caseId> "analyst justification text"

    args = sys.argv[1:]
    if not args:
        logger.error("Usage: kyc <caseId> | override <caseId> <comments>")
        sys.exit(1)

    mode = args[0]
    if mode == "kyc":
        test_kyc_flow(case_id=args[1])
    elif mode == "override":
        test_override_flow(case_id=args[1], analyst_comments=args[2])
    else:
        logger.error("Unknown mode %r. Use 'kyc' or 'override'.", mode)
        sys.exit(1)