AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Roles Stack for Agent Core Runtime'

Parameters:
  StackName:
    Type: String
    Description: Name of the stack
  BaseStackName:
    Type: String
    Description: Name of the Base stack

Resources:
  AgentExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StackName}-agent-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentCoreRuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CreateBedrockAgentCoreNetworkServiceLinkedRolePermissions
                Effect: Allow
                Action: iam:CreateServiceLinkedRole
                Resource: arn:aws:iam::*:role/aws-service-role/network.bedrock-agentcore.amazonaws.com/AWSServiceRoleForBedrockAgentCoreNetwork
                Condition:
                  StringEquals:
                    iam:AWSServiceName: network.bedrock-agentcore.amazonaws.com
              - Sid: GetResourceApiKey
                Effect: Allow
                Action: bedrock-agentcore:GetResourceApiKey
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:token-vault/default"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default/workload-identity/agent-*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:token-vault/default/apikeycredentialprovider/*"
              - Sid: GetResourceOauth2Token
                Effect: Allow
                Action: bedrock-agentcore:GetResourceOauth2Token
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:token-vault/default/oauth2credentialprovider/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:token-vault/default"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default/workload-identity/agent-*"
              - Sid: WorkloadAccessToken
                Effect: Allow
                Action:
                  - bedrock-agentcore:GetWorkloadAccessToken
                  - bedrock-agentcore:GetWorkloadAccessTokenForUserId
                  - bedrock-agentcore:GetWorkloadAccessTokenForJWT
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default/workload-identity/agent-*"
              - Sid: CodeInterpreter
                Effect: Allow
                Action:
                  - bedrock-agentcore:DeleteCodeInterpreter
                  - bedrock-agentcore:GetCodeInterpreterSession
                  - bedrock-agentcore:StopCodeInterpreterSession
                  - bedrock-agentcore:GetCodeInterpreter
                  - bedrock-agentcore:ListCodeInterpreterSessions
                  - bedrock-agentcore:StartCodeInterpreterSession
                  - bedrock-agentcore:InvokeCodeInterpreter
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:code-interpreter-custom/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:aws:code-interpreter/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:code-interpreter/*"
              - Sid: CloudWatchMetrics
                Effect: Allow
                Action: cloudwatch:PutMetricData
                Resource: '*'
                Condition:
                  StringEquals:
                    cloudwatch:namespace: bedrock-agentcore
              - Sid: CoreServices
                Effect: Allow
                Action:
                  - bedrock-agentcore:InvokeAgentRuntime
                  - secretsmanager:GetSecretValue
                  - logs:DescribeLogStreams
                  - ecr:GetDownloadUrlForLayer
                  - bedrock:InvokeModel
                  - ecr:BatchGetImage
                  - bedrock:InvokeModelWithResponseStream
                  - logs:CreateLogGroup
                Resource:
                  - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:bedrock-agentcore-identity!default/oauth2/*"
                  - "arn:aws:bedrock:*::foundation-model/*"
                  - "arn:aws:bedrock:*:*:inference-profile/*"
                  - !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:runtime/*"
              - Sid: GlobalServices
                Effect: Allow
                Action:
                  - xray:PutTelemetryRecords
                  - s3:*
                  - bedrock-agentcore:CreateMemory
                  - xray:GetSamplingRules
                  - ecr:GetAuthorizationToken
                  - xray:GetSamplingTargets
                  - xray:PutTraceSegments
                Resource: '*'
              - Sid: MemoryAndLogs
                Effect: Allow
                Action:
                  - bedrock-agentcore:GetEvent
                  - bedrock-agentcore:CreateEvent
                  - bedrock-agentcore:DeleteEvent
                  - bedrock-agentcore:ListEvents
                  - logs:PutLogEvents
                  - bedrock-agentcore:ListMemoryRecords
                  - bedrock-agentcore:GetMemoryRecord
                  - logs:CreateLogStream
                  - bedrock-agentcore:GetMemory
                  - bedrock-agentcore:RetrieveMemoryRecords
                  - bedrock-agentcore:ListActors
                  - bedrock-agentcore:ListSessions
                  - bedrock-agentcore:ListMemories
                  - bedrock-agentcore:DeleteMemoryRecord
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:memory/*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*"
              - Sid: DescribeLogGroups
                Effect: Allow
                Action: logs:DescribeLogGroups
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
              - Sid: CodeInterpreterManagement
                Effect: Allow
                Action:
                  - bedrock-agentcore:ListCodeInterpreters
                  - bedrock-agentcore:CreateCodeInterpreter
                Resource:
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:code-interpreter-custom/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:aws:code-interpreter/*"
                  - !Sub "arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:code-interpreter/*"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StackName}-codebuild-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: CodeBuildLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: S3SourceAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${BaseStackName}-*"
                  - !Sub "arn:aws:s3:::${BaseStackName}-*/*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StackName}-lambda-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: '*'

Outputs:
  AgentExecutionRoleArn:
    Description: ARN of the agent execution role
    Value: !GetAtt AgentExecutionRole.Arn
    Export:
      Name: !Sub "${StackName}-AgentExecutionRoleArn"

  CodeBuildRoleArn:
    Description: ARN of the CodeBuild role
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: !Sub "${StackName}-CodeBuildRoleArn"

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub "${StackName}-LambdaExecutionRoleArn"
